ROOT_PATH = os.path.dirname(os.path.abspath(__file__))
ACCOUNTS_PATH = os.path.join(ROOT_PATH, 'ACCOUNTS')
SUCCESS_PATH = os.path.join(ROOT_PATH, 'SUCCESS')
FAILED_PATH = os.path.join(ROOT_PATH, 'FAILED')



IMG_HEIGHT = 150
IMG_WIDTH = 150

IMG_MIN_HEIGHT_FIND = 80
IMG_MIN_WIDTH_FIND = 80



BINARY_FILTER_CLASSES = ['GIRL', 'LIT']
CATEGORIZER_CLASSES = ['ASIAN', 'BRUNETTE', 'DREADLOCK', 'GINGER', 'MULATTO']